apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-scheduler
  namespace: kube-system
  labels:
    app: custom-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-scheduler
  template:
    metadata:
      labels:
        app: custom-scheduler
    spec:
      containers:
      - name: custom-scheduler
        image: custom-scheduler:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 10259
        args: ["-v=${LOG_LEVEL}"]
        env:
        - name: LOG_LEVEL
          value: "2"
        volumeMounts:
        - name: custom-scheduler-config
          mountPath: /etc/custom-scheduler
      volumes:
      - name: custom-scheduler-config
        configMap:
          name: custom-scheduler-config
      serviceAccountName: custom-scheduler
